# Generated by Django 5.0.1 on 2024-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, null=True)),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=26)),
                ('dateCreation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
