# Generated by Django 5.0.1 on 2024-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='category',
            field=models.CharField(choices=[('Physique', 'Physique'), ('Mathématique', 'Mathématique'), ('Chimie', 'Chimie'), ('Science', 'Science'), ('Enfant', 'Enfant'), ('Informatique', 'Informatique')], max_length=190, null=True),
        ),
    ]
